language: node_js
node_js:
- '6'
after_success: npm run coverage
deploy:
  provider: npm
  email: fptavares@gmail.com
  api_key:
    secure: oGqxnm6lMhOvrgWkUwINqdWuABz2x7WuSuXVAyiv1PeFDPrOmO+c91luXd9rIIRwIxEbhOj2Sb/gEWswxDCbCMMKHpXdOVpzXRoy4/G4z2pb3qtz5k2aPza/kNfxSgndwljYF3+l4L+tZ2wkioAoBAHxHYpHekO/dMXxsm/yAqPQhEFSgHP4vVKEgm7mD8LS83PIWBVOgiIvNlOVcW9M9ZwRWHd57VJEaqpqZpvl5kJNer5WqYGBWx7ryGYdUFENktE5tLX+divm1LLSoJ6bYcJtpmZH4TAAJziONr7ZKN+y90OfRVg53FSO6lVbSnu3t8CS2bWn6AcazehJq+Q1TojJCcNdZCFa6GbPOC3zRQkeKesGEp317Ngputxwf9k2LiKqnmkm8PAMrMB7BPatVjLVg5jJclMhko2fpn+2w7OY3H2DEhAwlP48gzccYOlg0yKyjdDo08qDtVbrbUPQmCy8GpKowNJrTpK0Ch1nw8Qe1ws6euTYfoWyVB3cPNgiOFP9hLzn0OWq/bdevrRwrZzLIGZglToFe4OX3J8MJqh19h76mupIygZHaTskQV3Od4AZ8GNLezj8mXDVNu2+UQqKuHvRCjcVasEX4d6VSUUOH2moANx4oWz6R+W/KBGTu71dvPQ836hJkUGGBvdCWhBd5BikaorqlAajB0PRq3g=
  on:
    tags: true
    repo: modofunjs/modofun-trace-agent-plugin
